server:
  port: 8001
  servlet:
    context-path: /spring-cloud-sqs-dlq-pattern-implementation

cloud:
  aws:
    region:
      static: sa-east-1
    access-key: default_access_key
    secret-key: default_secret_key
    dynamodb:
      endpoint: http://localhost:4566
    sqs:
      source-sqs-with-attached-dlq:
        url: http://localhost:4566/000000000000/source-sqs-with-attached-dlq
      source-sqs-without-attached-dlq:
        url: http://localhost:4566/000000000000/source-sqs-without-attached-dlq
        reprocess-max-count: 3
      dlq-for-source-sqs-without-attached-dlq:
        url: http://localhost:4566/000000000000/dlq-for-source-sqs-without-attached-dlq